spring:
  application:
    name: doodle-backend
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost:9092/~/doodle
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console
  main:
    web-application-type: reactive

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
